### ISSUE TITLE
Cannot find module '@/lib/utils' after upgading from 2.1.0 to 2.2.0+

### ISSUE THREAD

**Issue by xak2000** [radix-vue/shadcn-vue#1684]
I changed the version of `shadcn-nuxt` dependency from `2.1.0` to `2.2.0` in my `package.json` and installed the new dependencies. But now every file that tries to import from `@/lib/utils` doesn't work.

> Cannot find module '@/lib/utils' or its corresponding type declarations.

I still have `components.json` in my root as before with this content:

```
{
  "$schema": "https://shadcn-vue.com/schema.json",
  "style": "default",
  "typescript": true,
  "tailwind": {
    "config": "tailwind.config.ts",
    "css": "app/assets/css/tailwind.css",
    "baseColor": "slate",
    "cssVariables": true,
    "prefix": ""
  },
  "aliases": {
    "components": "@/components",
    "utils": "@/lib/utils",
    "ui": "@/components/ui",
    "lib": "@/lib",
    "composables": "@/composables"
  }
}
```

Basicaly nothing is changed in my project between upgrading from 2.1.0 to 2.2.0.

I should mention that I use `compatibilityVersion: 4` in nuxt config (maybe that matters), so I use the new directory structure from Nuxt 4 with Nuxt 3.

I noticed that in 2.1.0 there was a file `.nuxt/shadcn-nuxt/utils.ts`. Now it is missing.

I do not understand what is going on and where this file should came from in version 2.2.0+.

I tried the latest version 2.4.3 - same problem.

I see the commint ddd4ec3 that was released with 2.2.0 and that is probably causing this issue, but I do not understand how it is supposed to work now and why nobody else is having this problem?

**Comment by xak2000** [comment]
Another note: after upgrading from Nuxt 3.18.1 to 3.21.1 (and keeping shadcn-nuxt 2.1.0) the server stopped to build on Google Clould Build with this error:

> ■ Nuxt build error: Error: [vite:load-fallback] Could not load /usr/src/app/app//lib/utils (imported by app/components/modal/ModalContainer.vue?vue&type=script&setup=true&lang.ts): ENOENT: no such file or directory, open '/usr/src/app/app//lib/utils'

The local build on Windows 11 worked fine.

The import line in `ModalContainer.vue` was:

```ts
import { cn } from '@/lib/utils'
```

It works in DEV and local build, but not the build on Google Cloud Build machine (maybe because there is Linux, while my local build was on Windows).

To fix the problem I copied the contents of `.nuxt/shadcd-nuxt/utils.ts` file into new `app/utils/cn.ts` file and changed all the imports to `import { cn } from '~/utils/cn'`. Now the build works on both local Windows machine and remote Linux machine.

Probably with this change I will be able to upgrade to shadcn-nuxt 2.2.0+ as I don't use the utils from this module anymore.

But, the question is still relevant: what is the intended way to use `cn` util starting from shadcn-nuxt 2.2.0+? Do I expected to copy it to my local project? I doubt it. If feel there is somethinfg wrong, but can't understand what is it.

**Comment by sadeghbarati** [comment]
The latest version of `shadcn-nuxt` is **2.4.3**

Please try latest `shadcn-nuxt` https://npmx.dev/package/shadcn-nuxt

And add utils manually to your project for now

**Comment by xak2000** [comment]
> The latest version of `shadcn-nuxt` is **2.4.3**
> 
> Please try latest `shadcn-nuxt` https://npmx.dev/package/shadcn-nuxt

Thanks! I tried the latest version 2.4.3 - same problem. "Cannot find module '@/lib/utils'".

> And add utils manually to your project for now

That is exactly what I did. This way both 2.1.0 and 2.4.3 work.

But, is it intentionally? I remember in an old `shadcn-nuxt` version the utils were supposed to be created manually in a project, later this was changed and `utils` were delivered together with `shadcn-nuxt`. What is the situation now? I mean, am I supposed to create my own utils or they are still supposed to be delivered with `shadcn-nuxt`? Is it documented?

**Comment by sadeghbarati** [comment]
Please share your project if it's possible

**Comment by xak2000** [comment]
No, it's not possible. Maybe I will try to create a reproduce later, if have more time.

But, I asked a simple question: what is the current situation with `lib/utils`? Is it **intended** to be copy/pasted into the project? Or it is **supposed to work** using `import { cn } from '@/lib/utils'`? I.e. what is the standard out-of-the-box intended way?

Without an answer, I can't do any further research because I don't even understand how this is **supposed** to work.

**Comment by jjlorenzo** [comment]
In case it is related with this, I've found that with `2.4.3` the `lib/utils.ts` is created inthe wrong dir.

```
❯ pnpm dlx shadcn-vue@latest init
...
✔ Created 1 file:
  - src/lib/lib/utils.ts                                                                                                                                                                                                                                           ...
```

**Comment by ad80352** [comment]
Same problem here.

Later I realized when you set module/moduleResolution to `NodeNext/nodenext` in `tsconfig.json`,
TypeScript treats each non-package relative/alias import as “requiring a .js file extension,”
otherwise it will report a module not found error.

So I changed my `tsconfig.json` setting to `ESNext/bundler`:
```
{
	"compilerOptions": {
		...
		"module": "ESNext",
		"moduleResolution": "bundler",
		...
	},
	"include": ["src"]
}
```

Now resolved.

**Comment by xak2000** [comment]
@ad80352 So, it is not "same problem" then, but a totally different problem.

**Comment by ad80352** [comment]
> [@ad80352](https://github.com/ad80352) So, it is not "same problem" then, but a totally different problem.


My fault, same part is "Cannot find module '@/lib/utils'"

**Comment by xak2000** [comment]
It's OK. I just wanted to emphasize that it is a different problem to avoid potential confusion.

The problem described here is related to `shadcn-nuxt` module. And in Nuxt the module type is already `ESNext`.

**Comment by jjlorenzo** [comment]
> In case it is related with this, I've found that with `2.4.3` the `lib/utils.ts` is created inthe wrong dir.
> 
> ```
> ❯ pnpm dlx shadcn-vue@latest init
> ...
> ✔ Created 1 file:
>   - src/lib/lib/utils.ts                                                                                                                                                                                                                                           ...
> ```

Yes, it's a different problem, in my case, I've found that despite you can define aliases in the `components.json` the cli still requires the presence of the `@/*` import path.

**Comment by hanspr** [comment]
I'm having same issues when creating new projects, I'm very new to this framework but for what I can see the location of the `utils.ts` file has changed.

my `components.json` file has:

```
{
    "$schema": "https://shadcn-vue.com/schema.json",
    "style": "new-york",
    "font": "inter",
    "typescript": true,
    "tailwind": {
        "config": "",
        "css": "app/assets/css/tailwind.css",
        "baseColor": "neutral",
        "cssVariables": true,
        "prefix": ""
    },
    "iconLibrary": "lucide",
    "rtl": false,
    "aliases": {
        "components": "@/components",
        "utils": "@/lib/utils",
        "ui": "@/components/ui",
        "lib": "@/lib",
        "composables": "@/composables"
    },
    "registries": {}
}
```

And found the imported `utils.js` file here:

```
app/lib/new-york-v4/lib/utils.ts
```

And the installed modules expect to find it in 

```
app/lib
```

By copying the file from `app/lib/new-york-v4/utils.ts` to `app/lib` it works

As I said, I'm not very familiar with all this probably there is the need of a different pattern in the `components.json` to find libraries in nested directories.
